ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';
CREATE DATABASE IF NOT EXISTS Amazon;
CREATE DATABASE IF NOT EXISTS ebay;
CREATE DATABASE IF NOT EXISTS user;
FLUSH PRIVILEGES;
